version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - "3000:80"

  sonarqube:
    image: sonarqube:lts-community
    container_name: smartlogix-sonarqube
    ports:
      - "9000:9000"
    environment:
      # Habilitamos el análisis anónimo sin tokens
      SONAR_FORCEAUTHENTICATION: "false"

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: smartlogix-scanner
    depends_on:
      sonarqube:
        condition: service_started 
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_TOKEN: sqp_057e6d5aedcc34fca9e1c2b0c0dbe07f21e7c249