// gameImages.ts
export const gameImages: Record<string, string> = {
  "Resident Evil 0": "https://cdn.cloudflare.steamstatic.com/steam/apps/359320/header.jpg",
  "Resident Evil 1 Remake": "https://cdn.cloudflare.steamstatic.com/steam/apps/304240/header.jpg",
  "Resident Evil 2 Remake": "https://cdn.cloudflare.steamstatic.com/steam/apps/883710/header.jpg",
  "Resident Evil 3 Remake": "https://cdn.cloudflare.steamstatic.com/steam/apps/952060/header.jpg",
  "Resident Evil 4 Remake": "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg",
  "Resident Evil 5": "https://cdn.cloudflare.steamstatic.com/steam/apps/21690/header.jpg",
  "Resident Evil 6": "https://cdn.cloudflare.steamstatic.com/steam/apps/221040/header.jpg",
  "Resident Evil 7: Biohazard": "https://cdn.cloudflare.steamstatic.com/steam/apps/418370/header.jpg",
  "Resident Evil Village": "https://cdn.cloudflare.steamstatic.com/steam/apps/1196590/header.jpg",
  "The Last of Us Part I": "https://cdn.cloudflare.steamstatic.com/steam/apps/1888930/header.jpg",
  "The Last of Us Part II": "https://cdn.cloudflare.steamstatic.com/steam/apps/2531310/header.jpg",
  "God of War (2018)": "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg",
  "God of War Ragnarok": "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg",
  "Ghost of Tsushima": "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg",
  "Ghost of Tsushima Director's Cut": "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg",
  "Need for Speed Most Wanted": "https://cdn.cloudflare.steamstatic.com/steam/apps/24870/header.jpg",
  "Need for Speed Heat": "https://cdn.cloudflare.steamstatic.com/steam/apps/1222680/header.jpg",
  "Need for Speed Unbound": "https://cdn.cloudflare.steamstatic.com/steam/apps/1846380/header.jpg",
  "Grand Theft Auto IV": "https://cdn.cloudflare.steamstatic.com/steam/apps/12210/header.jpg",
  "Grand Theft Auto V": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg",
  "Grand Theft Auto VI": "https://cdn.cloudflare.steamstatic.com/steam/apps/2922880/header.jpg",
  "Red Dead Redemption 2": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
  "The Witcher 3: Wild Hunt": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
  "Cyberpunk 2077": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
  "Elden Ring": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
  "Hollow Knight": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg",
  "Hades": "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg",
  "Spider-Man 2": "https://cdn.cloudflare.steamstatic.com/steam/apps/2119490/header.jpg",
  "Horizon Forbidden West": "https://cdn.cloudflare.steamstatic.com/steam/apps/2420110/header.jpg",
  "Resident Evil Requiem": "https://cdn.cloudflare.steamstatic.com/steam/apps/3764200/header.jpg",
}